apiVersion: v1
kind: Pod
metadata:
  name: todoapp
  namespace: todoapp
  labels:
    app.kubernetes.io/name: todoapp
spec:
  containers:
  - name: todoapp
    image: killingrace/todoapp:3.0.0 #my own private account
    ports:
      - containerPort: 8000
    livenessProbe:
      httpGet:
        path: /api/health/
        port: 8000
      initialDelaySeconds: 15
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: /api/ready/
        port: 8000
      initialDelaySeconds: 10
      periodSeconds: 5